const Type = {
  Grass: 1,
  Fire: 2,
  Wather: 3,
  Electric: 4,
  Ground: 5,
  Bug: 6,
  Rock: 7,
  Poison: 8,
};

const PokemonList = [
  {
    name: "Bulbasaur",
    description: "Generation I",
    no: 1,
    type: [Type.Grass, Type.Poison],
    hp: 3,
    atk: 3,
    def: 3,
    satk: 4,
    sdef: 4,
    spd: 3,
    total: 9,
  },
  {
    name: "Charmander",
    description: "Generation I",
    no: 4,
    type: [Type.Fire],
    hp: 3,
    atk: 4,
    def: 3,
    satk: 4,
    sdef: 3,
    spd: 4,
    total: 9,
  },
  {
    name: "Squirtle",
    description: "Generation I",
    no: 7,
    type: [Type.Wather],
    hp: 3,
    atk: 3,
    def: 4,
    satk: 3,
    sdef: 4,
    spd: 3,
    total: 9,
  },
  {
    name: "Pikachu",
    description: "Generation I",
    no: 25,
    type: [Type.Electric],
    hp: 3,
    atk: 4,
    def: 3,
    satk: 3,
    sdef: 3,
    spd: 6,
    total: 9,
  },
  {
    name: "Geodude",
    description: "Generation I",
    no: 74,
    type: [Type.Ground, Type.Rock],
    hp: 3,
    atk: 5,
    def: 6,
    satk: 2,
    sdef: 2,
    spd: 2,
    total: 9,
  },
  {
    name: "Abra",
    description: "Generation I",
    no: 6,
    type: [Type.Ground, Type.Rock],
    hp: 1,
    atk: 7,
    def: 9,
    satk: 0,
    sdef: 5,
    spd: 2,
    total: 255,
  },
];

const PokemonMap = PokemonList.reduce((acc, p) => {
  acc[p.name] = p;
  return acc;
}, {});

export { PokemonList, PokemonMap };
